[application]
base_path = "dioxus_ia"
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "Imager"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "com.sura.imager"
publisher = "Surasia"
icon = ["icons/128x128@2x.png", "icons/icon.ico", "icons/icon.icns"]
